# Generated by Django 3.2.5 on 2021-07-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contato_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
